development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: kafai
  password: 225321

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: kafai
  password: 225321
